version: '3'

services:
  pap:
    build:
      context: '.'
      dockerfile: Dockerfile.pap
      args:
        WWWGROUP: '${WWWGROUP}'
    depends_on:
      - pap_db
    environment:
      APP_PORT: 444
      APP_SERVICE: pap
    hostname: pap.localdev
    ports:
      - '${APP_PORT:-444}:443'
    tty: true
    volumes:
      - './pap.conf:/etc/apache2/sites-enabled/pap.conf'
      - './xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './ssl/:/etc/apache2/ssl/'
      - '.:/var/www/html'

  pap_demo_client:
    build:
      context: '.'
      dockerfile: Dockerfile.pap-demo-client
    hostname: pap-demo-client.localdev
    ports:
      - '${DEMO_CLIENT_PORT:-445}:443'
    volumes:
      - './demo-client:/usr/local/apache2/htdocs/'
      - './ssl/pap-demo-client.localdev.crt:/usr/local/apache2/conf/server.crt'
      - './ssl/pap-demo-client.localdev.key:/usr/local/apache2/conf/server.key'

  pap_db:
    container_name: pap_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pap
    image: 'postgres:12'
    ports:
      - '5552:5432'
