name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: use .env.testing
        run: cp .env.testing .env

      - name: Copy clients.json
        run: cp clients.json.example clients.json

      - name: Generate SSL certs
        run: sh ./scripts/generate-certs.sh

      - name: Generate JWT key
        run: sh ./scripts/generate-jwt-key.sh

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Execute tests with Code Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover tests/coverage.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2.26.0
        continue-on-error: true
        with:
          workflow: .github/workflows/coverage-report.yml # this file
          branch: main
          name: coverage-report
          path: tests/base

      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tests/coverage.xml

      - name: Coverage Report as Comment (Clover)
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: tests/coverage.xml
          base-file: tests/base/coverage.xml
