name: Notify RDObeheer on config-changes

on:
  push:
    branches: [ main ]
    paths: [ '.env.example' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Diff configfiles
        run: git diff main~1:.env.example .env.example > env.conf.diff
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.prolocation.net
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions ${{github.repository}}
          to: fyi@rdobeheer.nl
          from: Github actions <${{secrets.MAIL_USERNAME}}>
          secure: false
          body: >
             Config change in ${{github.repository}}
          attachments: inge3.conf.diff,env.conf.diff
          ignore_cert: false
          convert_markdown: false
