name: Node - npm run lint

on:
  push:
    branches: [main, develop, release/**, hotfix/**]
  pull_request:
    branches: [main, develop, release/**, hofix/**]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run audit -- --production
      - run: npm run build
      - run: npm run lint
